# Generated by Django 3.0.6 on 2020-05-22 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('nationalite', models.CharField(max_length=25)),
                ('ville', models.CharField(max_length=25)),
                ('universite', models.CharField(max_length=50)),
                ('diplome', models.CharField(max_length=15)),
                ('annee', models.IntegerField()),
                ('activites', models.CharField(max_length=50)),
                ('RateEnseignant', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('RateAdministratif', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('RateBDE', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aspects', models.TextField(blank=True)),
                ('autoformation', models.BooleanField()),
                ('objectifs', models.BooleanField()),
            ],
        ),
    ]
